# Generated by Django 2.2 on 2021-10-16 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LogRegApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote_desc', models.TextField()),
                ('author', models.CharField(max_length=24)),
                ('like', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quote_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='LogRegApp.User')),
            ],
        ),
    ]
