# Generated by Django 2.2 on 2021-10-17 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='like',
        ),
    ]
